### ISSUE TITLE
key changed, this no longer works...

### ISSUE THREAD

**Issue by maceip** [rusq/osx-callhistory-decryptor#13]
macos 13.0.1

./osx-callhistory-decryptor
MacOS X Call History Decryptor v.0.0-development © 2018-2021 rusq
Based on Call History Decryptor © 2016 n0fate
2023/01/21 10:07:33 *** database filename: "/Users/x/Library/Application Support/CallHistoryDB/CallHistory.storedata"
2023/01/21 10:07:33 *** temporary file (will be removed): "/var/folders/nn/pztg8p51689c1xx06wv2zdg40000gn/T/callhistory198174384"
Enter your account password to access keychain when prompted...
2023/01/21 10:07:33 key is not supplied: make sure you have supplied the key via -k or KEY env variable

I checked in keychain but didnt find a callhistory key

**Comment by rusq** [comment]
Hey @maceip, thanks for the report.  I did find the key in the keychain, 
<img width="708" alt="image" src="https://user-images.githubusercontent.com/16064414/214265801-9d81ff44-bec2-4078-acc6-dce6ae513bb7.png">

but confirmed that due to recent changes it does not work (see details in #12).  As I noted there, I will have a look, but can't promise it will work.  But please let me know if you find the solution or alternative project that does the same on the recent version of OSx.

And if I fix this, I'll update this issue.

**Comment by rusq** [comment]
Please download the [new release](https://github.com/rusq/osx-callhistory-decryptor/releases/tag/v1.2.0), and run it with `-no-key` option.

It may require `sudo` as the CallHistory file is os protected.
